server:
  port: ${PORT:8080}
  max-http-request-header-size: 64KB

spring:
  application:
    name: fixmate-api-gateway

  cloud:
    gateway:
      httpclient:
        max-header-size: 64KB

      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      globalcors:
        add-to-simple-url-handler-mapping: false
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "https://fixmate-frontend-opal.vercel.app"
            allowedMethods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"

      routes:
        - id: fixmate-backend
          uri: lb://FIXMATE-BACKEND
          predicates:
            - Path=/api/v1/**,/v3/api-docs/**,/swagger-ui/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}